name: Build Test Image and Test

# Run on a push to main
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build Test Image and Test
    timeout-minutes: 30
    steps:

        # checkout Repo
        - name: Checkout Repo
          uses: actions/checkout@v2

        # Set up Docker
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        # Build dockerfiles
        - name: Build Dockerfiles
          run: docker build -f test.Dockerfile .
